import Link from "next/link";
import { getManualInstructions } from "@/lib/user-prefs";
import { getBusinessProfile } from "@/lib/business-profile";
import { currentUser } from "@/lib/auth";
import { SignedOut } from "@/components/settings/signed-out";
import { InstructionsForm } from "@/components/settings/instructions-form";
import { FiCpu, FiRefreshCw } from "@/components/ui/icons";

export const metadata = { title: "Instructions" };

export default async function InstructionsPage() {
  const user = await currentUser();
  if (!user) return <SignedOut />;

  const [instructions, business] = await Promise.all([
    getManualInstructions(user.id),
    getBusinessProfile(user.id),
  ]);

  return (
    <div className="mx-auto w-full max-w-[760px]">
      <p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-accent">
        AI behavior
      </p>
      <h1 className="mt-1 text-[24px] font-semibold tracking-[-0.03em] text-ink">
        Instructions
      </h1>
      <p className="mt-1.5 max-w-[62ch] text-[13.5px] leading-relaxed text-ink-3">
        Manual instructions are yours to edit. Auto Instructions are generated from your
        Business profile and update themselves whenever Trove analyzes the business again.
      </p>

      <section className="mt-6 overflow-hidden rounded-[22px] border border-violet-400/20 bg-gradient-to-br from-violet-500/[0.10] via-fuchsia-500/[0.05] to-sky-500/[0.08] shadow-[var(--sh-1)]">
        <div className="flex flex-col gap-3 border-b border-line/80 px-5 py-4 sm:flex-row sm:items-center sm:justify-between">
          <div className="flex items-start gap-3">
            <span className="grid size-10 shrink-0 place-items-center rounded-2xl bg-violet-500/10 text-violet-600 ring-1 ring-violet-400/20 dark:text-violet-300">
              <FiCpu size={18} />
            </span>
            <div>
              <div className="flex flex-wrap items-center gap-2">
                <h2 className="text-[14px] font-semibold text-ink">Auto Instructions</h2>
                <span className="rounded-full border border-emerald-400/20 bg-emerald-500/10 px-2 py-0.5 text-[9.5px] font-bold uppercase tracking-[0.1em] text-emerald-700 dark:text-emerald-300">
                  Auto synced
                </span>
              </div>
              <p className="mt-1 text-[11.5px] leading-relaxed text-ink-4">
                Generated by Trove from {business.businessName ? business.businessName : "your Business profile"}.
                Already applied automatically to chat, tools, agents, and the builder.
              </p>
            </div>
          </div>

          <Link
            href="/settings/business"
            className="inline-flex h-9 shrink-0 items-center justify-center gap-1.5 rounded-xl border border-violet-400/20 bg-raised/75 px-3 text-[11.5px] font-semibold text-violet-700 transition hover:bg-raised dark:text-violet-300"
          >
            <FiRefreshCw size={12} />
            Update business
          </Link>
        </div>

        <div className="p-5">
          {business.instructions.trim() ? (
            <pre className="max-h-[360px] overflow-y-auto whitespace-pre-wrap rounded-2xl border border-line bg-sunk/65 p-4 font-sans text-[12.5px] leading-relaxed text-ink-2">
              {business.instructions}
            </pre>
          ) : (
            <div className="rounded-2xl border border-dashed border-line-strong bg-sunk/50 p-5">
              <p className="text-[13px] font-medium text-ink-2">
                No Auto Instructions yet.
              </p>
              <p className="mt-1 text-[12px] leading-relaxed text-ink-4">
                Add a business name, URL, or profile file and Trove will analyze it,
                generate the business instructions, save them here, and start using them automatically.
              </p>
              <Link
                href="/settings/business"
                className="mt-3 inline-flex rounded-xl bg-accent-soft px-3 py-2 text-[11.5px] font-semibold text-accent transition hover:brightness-105"
              >
                Set up Business profile
              </Link>
            </div>
          )}
        </div>
      </section>

      <section className="mt-5 rounded-[22px] border border-line-strong bg-raised p-5 shadow-[var(--sh-1)] sm:p-6">
        <div className="mb-5">
          <p className="text-[11px] font-semibold uppercase tracking-[0.12em] text-ink-4">
            Manual layer
          </p>
          <h2 className="mt-1 text-[15px] font-semibold text-ink">
            Your instructions
          </h2>
          <p className="mt-1 text-[12px] leading-relaxed text-ink-4">
            These are the old/manual instructions. Saving them never removes the Auto Instructions above.
          </p>
        </div>
        <InstructionsForm initial={instructions} />
      </section>
    </div>
  );
}
